name: Functional Tests
description: Functional Tests

runs:
  using: "composite"
  steps:
    - run: -
        trap 'cat log.txt' err
        bash ./.ci/scripts/test.sh
        trap - err
      shell: bash