name: Functional Tests
description: Functional Tests

runs:
  using: "composite"
  steps:
    - run: sudo apt-get install libunwind-dev
      shell: bash
    - run: npm install
      shell: bash
    - run: |
        trap 'cat log.txt' err
        node tests/test.js 2> log.txt
        cat log.txt | grep -P 'PID \d+ received a SIGSEGV'
        trap - err
      shell: bash