name: Pull request checks

on: [pull_request]

jobs:
  build-and-run-images:
    name: Build and Run ${{ matrix.image }} image - Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: ['14.17.0', '12.16.3', '12.20.0']
        image: ['alpine', 'base', 'base-no-libunwind', 'base-partial-no-libunwind']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/build-and-run
        with:
          IMAGE: ${{ matrix.image }} 
          NODE_VERSION: ${{ matrix.node-version }}