name: Develop branch push checks

on:
  push:
    branches:
      - develop

jobs:
  build-and-run-images:
    name: Build and Run ${{ matrix.image }} image - Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: ['12.22.8', '14.19.3', '16.17.0']
        image: ['alpine', 'base', 'base-no-libunwind', 'base-partial-no-libunwind', 'base-no-pkg-config']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/build-and-run
        with:
          IMAGE: ${{ matrix.image }} 
          NODE_VERSION: ${{ matrix.node-version }}