name: Develop branch push checks

on:
  push:
    branches:
      - develop

jobs:
  functional-tests:
    name: Functional Tests - Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: ['14.17.0', '12.16.3', '12.20.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/functional-tests

  build-and-run:
    needs: [functional-tests]
    name: Build and Run ${{ matrix.image }} image - Node.js v${{ matrix.node-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: ['12.18.1']
        image: ['alpine']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/build-and-run
        with:
          IMAGE: ${{ matrix.image }} 